steps:
    # build the container images
    - name: 'gcr.io/cloud-builders/docker'
      args:
        ['build', '-t', 'gcr.io/$PROJECT_ID/komatoproxy', './client']
    # - name: 'gcr.io/cloud-builders/docker'
    #   args: ['build', '-t', 'gcr.io/$PROJECT_ID/server', './server']
  
    # push the container images to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/komatoproxy']
    # - name: 'gcr.io/cloud-builders/docker'
    # args: ['push', 'gcr.io/$PROJECT_ID/server']
  
    # Deploy container images to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
        [
          'run',
          'deploy',
          'komatoproxy',
          '--image',
          'gcr.io/$PROJECT_ID/komatoproxy',
          '--region',
          'us-central1',
          '--platform',
          'managed',
          '--quiet',
          '--allow-unauthenticated',
        ]
    # - name: 'gcr.io/cloud-builders/gcloud'
    #   args:
    #     [
    #       'run',
    #       'deploy',
    #       'server',
    #       '--image',
    #       'gcr.io/$PROJECT_ID/server',
    #       '--region',
    #       'us-central1',
    #       '--platform',
    #       'managed',
    #       '--quiet',
    #     ]
  images:
    - gcr.io/$PROJECT_ID/komatoproxy
    # - gcr.io/$PROJECT_ID/server
  